stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
- docker:19.03.0-dind


build:
  stage: build
  image: docker
  tags:
  - rancher
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID .
    - docker push $CI_REGISTRY_IMAGE:$CI_PIPELINE_ID

deploy_to_rancher:
  stage: deploy
  image: dtzar/helm-kubectl
  tags:
  - rancher
  script:
    - sed -i "s/IMAGE_TAG/$CI_PIPELINE_ID/g;
              s/REPLICAS_COUNT/1/g;
              s/PASS_AD/$AD_PASSWORD/g" .ci/k8sdeploy.yaml
    - mkdir -p /root/.kube/
    - echo "$K8S_CONFIG" > /root/.kube/config
#    - kubectl create secret tls nginx-reverse-proxy --cert=.ci/rbundle.crt --key=.ci/r_private.key -n dev-tools
    - kubectl apply -f .ci/k8sdeploy.yaml -n self-service
